host: 0.0.0.0

sass:
  style: compressed

plugins:
  - jekyll-minifier
  - jekyll-autoprefixer
  
jekyll-minifier:
  compress_css: false
  uglifier_args:
    harmony: true

autoprefixer:
  only_production: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: Marloes te Riele
      og:
        img: /assets/img/og.png
        description: Verstand van verhalen én in het voetlicht brengen, specialist in pers en publiciteit, ervaring met de organisatie van evenementen, moeder, verbinder, zoekt graag de hete brij op en is bloednieuwsgierig.